#!/bin/sh

# Modify the user's shell configuration file
echo 'export LIQUIBASE_HOME=/opt/liquibase' >> "$HOME/.bashrc"
echo 'export PATH=$PATH:$LIQUIBASE_HOME' >> "$HOME/.bashrc"

# Load the updated configuration into the current shell session
. "$HOME/.bashrc"
