#!/bin/bash

# Define LIQUIBASE_HOME
LIQUIBASE_HOME="/opt/liquibase"

# Iterate through all user home directories
for user_home in /home/*; do
    if [ -d "$user_home" ]; then
        user=$(basename "$user_home")
        profile_file="$user_home/.profile"
        
        # Check if the .profile file exists for the user
        if [ -f "$profile_file" ]; then
            echo "Adding LIQUIBASE_HOME to .profile for user: $user"
            if grep -q "$LIQUIBASE_HOME" "$profile_file"; then
                echo "LIQUIBASE_HOME already in PATH for user: $user"
            else
                echo "export LIQUIBASE_HOME=$LIQUIBASE_HOME" | sudo tee -a "$profile_file"
                echo "export PATH=\$PATH:\$LIQUIBASE_HOME" | sudo tee -a "$profile_file"
                . "$profile_file"
            fi
        else
            echo "No .profile found for user: $user"
        fi
    fi
done