name: 'Setup AWS Vault'
description: 'Configure AWS credentials and retrieve secrets from vault'
outputs:
  vault-secrets:
    description: 'All vault secrets as environment variables'
    value: ${{ steps.vault-secrets.outputs.vault-secrets }}
runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.LIQUIBASE_VAULT_OIDC_ROLE_ARN }}
        aws-region: us-east-1

    - name: Get secrets from vault
      id: vault-secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          ,/vault/liquibase
        parse-json-secrets: true