name: Build & Deploy extension jar to GPM
# This action will download an extension from github repo, build it, and deploy it to GPM as version master-SNAPSHOT.

on:
  workflow_call:
    inputs:
      extension:
        description: "Extension to build"
        required: true
        default: ""
        type: string
      groupId:
        description: "Maven Group ID"
        default: "org.liquibase.ext"
        type: string
  workflow_dispatch:
    inputs:
      extension:
        description: "Extension to build"
        required: true
        default: ""
        type: string

# Add permissions for the default GITHUB_TOKEN
permissions:
  contents: write
  packages: write

jobs:
  delete-dependency-packages:
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ inputs.groupId }}.${{ inputs.extension }}
          package-type: "maven"
          min-versions-to-keep: 5 # Keep the last 5 versions so we don't break simultaneous builds
          delete-only-pre-release-versions: true

  build-and-deploy-extensions:
    needs: [delete-dependency-packages]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_USERNAME: "liquibot"
      GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Dependencies
        run: |
          git config --global credential.helper store
          echo "https://$GIT_USERNAME:$GIT_PASSWORD@github.com" > ~/.git-credentials
          git clone https://github.com/liquibase/${{ inputs.extension }}.git ${{ inputs.extension }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: "maven"
          gpg-private-key: ${{ secrets.GPG_SECRET }}
          gpg-passphrase: GPG_PASSPHRASE
        env:
          GPG_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}

      - name: Get GitHub App token
        id: get-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.LIQUIBASE_GITHUB_APP_ID }}
          private-key: ${{ secrets.LIQUIBASE_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ inputs.extension }}
          permission-packages: write

        #look for dependencies in maven
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: |
            [
              {
                "id": "liquibase",
                "url": "https://maven.pkg.github.com/liquibase/liquibase",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always"
                }
              },
              {
                "id": "liquibase-pro",
                "url": "https://maven.pkg.github.com/liquibase/liquibase-pro",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always"
                }
              },
              {
                "id": "extension-repo",
                "url": "https://maven.pkg.github.com/liquibase/${{ inputs.extension }}",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always"
                }
              }
            ]
          servers: |
            [
              {
                "id": "liquibase",
                "username": "liquibot",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              },
              {
                "id": "liquibase-pro",
                "username": "liquibot",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              },
              {
                "id": "extension-repo",
                "username": "liquibot",
                "password": "${{ steps.get-token.outputs.token }}"
              }
            ]

      - name: Build and deploy Extension to GPM
        env:
          GPG_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
          APP_TOKEN: ${{ steps.get-token.outputs.token }}
        run: |
          cd ${{ inputs.extension }}
          EXTENSION_VERSION="master-SNAPSHOT"
          mvn versions:set -DnewVersion=$EXTENSION_VERSION
          mvn clean install -DskipTests
            mvn deploy:deploy-file \
              -Dfile=./target/${{ inputs.extension }}-$EXTENSION_VERSION.jar \
              -Dsources=./target/${{ inputs.extension }}-$EXTENSION_VERSION-sources.jar \
              -Djavadoc=./target/${{ inputs.extension }}-$EXTENSION_VERSION-javadoc.jar \
              -DrepositoryId=extension-repo \
              -Durl=https://maven.pkg.github.com/liquibase/${{ inputs.extension }} \
              -DpomFile=pom.xml
            cd ..
