name: OWASP Scanner

on:
  workflow_call:
    inputs:
      repository:
        description: "Repository to scan"
        required: false
        type: string
        default: "liquibase"
      branch:
        description: "Branch to scan"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository to scan"
        required: false
        type: string
        default: "liquibase"
      branch:
        description: "Branch to scan"
        required: true
        type: string

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  scan:
    runs-on: ubuntu-22.04
    env:
      REPO_DIR: ${{ inputs.repository }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          role-to-assume: ${{ secrets.LIQUIBASE_VAULT_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Get secrets from vault
        id: vault-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@2cb1a461cbd4865ac4299648312e4704c646cd53 # v3.0.1
        with:
          secret-ids: |
            ,/vault/liquibase
          parse-json-secrets: true

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: liquibase/${{ inputs.repository }}
          ref: ${{ inputs.branch }}
          path: ${{ inputs.repository }}

      - name: Set up Java for publishing to GitHub Repository
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Set up Maven settings.xml
        uses: liquibase/build-logic/.github/actions/setup-maven-settings@main
        with:
          gpm-token: ${{ env.LIQUIBOT_PAT_GPM_ACCESS }}

      - name: Build project
        run: |
          cd "$REPO_DIR"
          mvn clean install -DskipTests

      - name: Run OWASP Dependency Check
        id: run_owasp
        env:
          NVD_API_KEY_VAL: ${{ env.NVD_API_KEY }}
        run: |
          cd "$REPO_DIR"
          mvn org.owasp:dependency-check-maven:aggregate -DnvdApiKey="$NVD_API_KEY_VAL" -DfailOnError=true

      - name: Upload OWASP Dependency-Check results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: owasp-dependency-check
          path: ${{ inputs.repository }}/target/dependency-check-report.html
