name: OWASP Scanner

on:
  workflow_call:
    inputs:
      repository:
        description: "Repository to scan"
        required: false
        type: string
        default: "liquibase"
      branch:
        description: "Branch to scan"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository to scan"
        required: false
        type: string
        default: "liquibase"
      branch:
        description: "Branch to scan"
        required: true
        type: string

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  scan:
    runs-on: ubuntu-22.04
    env:
      REPO_DIR: ${{ inputs.repository }}
    steps:
      - name: Configure AWS credentials for the liquibot-github-pat secret
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.VAULT_AWS_ACCOUNT_ID }}:role/vault-grouped-liquibot-github-pat-6
          aws-region: us-east-1

      - name: Get the liquibot-github-pat secret from vault
        uses: aws-actions/aws-secretsmanager-get-secrets@2297f9a879480a9e3af9b293ed15c70caf8e1c88 # v3.0.2
        with:
          secret-ids: |
            ,/vault/grouped/liquibot-github-pat
          parse-json-secrets: true

      - name: Configure AWS credentials for the nvd secret
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.VAULT_AWS_ACCOUNT_ID }}:role/vault-grouped-nvd
          aws-region: us-east-1

      - name: Get the nvd secret from vault
        uses: aws-actions/aws-secretsmanager-get-secrets@2297f9a879480a9e3af9b293ed15c70caf8e1c88 # v3.0.2
        with:
          secret-ids: |
            ,/vault/grouped/nvd
          parse-json-secrets: true

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: liquibase/${{ inputs.repository }}
          ref: ${{ inputs.branch }}
          path: ${{ inputs.repository }}

      - name: Set up Java for publishing to GitHub Repository
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Set up Maven settings.xml
        uses: liquibase/build-logic/.github/actions/setup-maven-settings@2660ba32055efd3301bcf624a3d60ca8b11cc482 # main
        with:
          gpm-token: ${{ env.LIQUIBOT_PAT_GPM_ACCESS }}

      - name: Build project
        run: |
          cd "$REPO_DIR"
          mvn clean install -DskipTests

      - name: Run OWASP Dependency Check
        id: run_owasp
        env:
          NVD_API_KEY_VAL: ${{ env.NVD_API_KEY }}
        run: |
          cd "$REPO_DIR"
          mvn org.owasp:dependency-check-maven:aggregate -DnvdApiKey="$NVD_API_KEY_VAL" -DfailOnError=true

      - name: Upload OWASP Dependency-Check results
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: owasp-dependency-check
          path: ${{ inputs.repository }}/target/dependency-check-report.html
