name: Release POM to Sonatype

on:
  workflow_call:
    secrets:
      SONATYPE_USERNAME:
        description: 'SONATYPE_USERNAME from the caller workflow'
        required: true
      SONATYPE_TOKEN:
        description: 'SONATYPE_TOKEN from the caller workflow'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: sonatype-nexus-staging
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Configure Git
        run: |
          git config user.name "liquibot"
          git config user.email "liquibot@liquibase.org"

      - name: Build release artifacts
        id: build-release-artifacts
        run: |
          mvn -B release:clean release:prepare -Darguments="-Dusername=liquibot -Dpassword=$GITHUB_TOKEN -Dmaven.javadoc.skip=true -Dmaven.test.skipTests=true -Dmaven.test.skip=true -Dmaven.deploy.skip=true" -DreleaseVersion=${{ github.event.inputs.liquibaseVersion }} -DpushChanges=false
          git reset HEAD~ --hard

      - name: Get Artifact ID
        id: get-artifact-id
        run: echo "artifact_id=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV

      - name: Download Release Artifacts
        uses: robinraju/release-downloader@v1.8
        with:
          tag: "${{ github.event.release.tag_name }}"
          filename: "${{ env.artifact_id }}-*"
          out-file-path: "."

      - name: Publish to Maven Central
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_TOKEN }}
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)          
          mvn -B org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy-file \
                      -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2/ \
                      -DrepositoryId=sonatype-nexus-staging \
                      -DpomFile=${{ env.artifact_id }}-${version}.pom \
                      -DgeneratePom=false \
                      -Dfile=${{ env.artifact_id }}-${version}.pom \
                      -Dsources=${{ env.artifact_id }}-${version}-sources.jar \
                      -Djavadoc=${{ env.artifact_id }}-${version}-javadoc.jar \
                      -Dfiles=${{ env.artifact_id }}-${version}-sources.jar.asc,${{ env.artifact_id }}-${version}-javadoc.jar.asc,${{ env.artifact_id }}-${version}.pom.asc \
                      -Dtypes=jar.asc,jar.asc,pom.asc \
                      -Dclassifiers=sources,javadoc,

  maven-release:
    needs: release
    uses: liquibase/build-logic/.github/workflows/extension-release-prepare.yml@v0.6.5
    secrets: inherit