
on:
  workflow_call:
    inputs:
      lb_flavor:
        required: false
        type: string
        default: 'pro'
      thisSha:
        required: false
        type: string
      thisBranchName:
        required: true
        type: string
      thisBranchFileName:
        required: true
        type: string
      thisRepositoryName:
        required: true
        type: string
      thisRepositoryOwner:
        required: true
        type: string

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.after}}
      - name: Built Code Cache
        uses: actions/cache@v3.0.1
        with:
          key: built-code-${{ github.run_number }}-${{ github.run_attempt }}
          path: ./**/target
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'adopt'
          cache: 'maven'

# - name: Download liquibase modules
#       uses: liquibase/action-download-artifact@v2-liquibase
#        with:
#          workflow: build.yml
#          workflow_conclusion: success
#          run_id: "${{ needs.setup.outputs.lastSuccessfulWorkflowId }}"
#          name: liquibase-modules
#          path: download
#          repo: liquibase/liquibase

      - name: Install liquibase oss modules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get repo information 
        run: |
          mvn -X org.liquibase.ext:liquibase-sdk-maven-plugin:0.9:install-snapshot "-Dliquibase.sdk.github.token=$GITHUB_TOKEN" "-Dliquibase.sdk.branchSearch=${{ inputs.thisBranchName }},master" "-Dliquibase.sdk.repo=liquibase/liquibase"  "-Dliquibase.sdk.skipFailedBuilds=true"

      - name: Build and Package
        run: mvn -B -Dbuild.pro.number=${{ github.run_number }} -Dbuild.pro.commit=${{ inputs.thisSha }} -Dbuild.pro.branch=${{ inputs.thisBranchName }} -DskipTests=true clean package

      - name: Save Keygen
        uses: actions/upload-artifact@v3
        with:
          name: licensing-keygen
          path: ./licensing/keygen/target/licensing-keygen-0-SNAPSHOT-assembly.zip

      - name: Save Module
        uses: actions/upload-artifact@v3
        with:
          name: liquibase-pro-modules
          path: ./pro/target/liquibase-pro-0-SNAPSHOT.jar

