name: Build For Liquibase

on:
  workflow_dispatch:
  schedule:
    - cron: "5 6 * * *"
  push:
    branches:
      - 'main'
  workflow_call:
    inputs:
      version:
        required: true
        description: 'Version to publish'
        type: string
      repository:
        required: true
        description: 'Repository to check out'
        type: string

jobs:
  build-test:
    name: Build and Test Extension
    uses: liquibase/build-logic/.github/workflows/pro-extension-build-for-liquibase.yml@DAT-18331
    secrets: inherit
    with:
      os: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      java: "[17, 21]"
      artifactPath: liquibase-checks
      combineJars: true
      repository: ${{ inputs.repository }}
      version: ${{ inputs.version }}
      extraLinuxCommand: |
        wget -q https://dl.min.io/server/minio/release/linux-amd64/minio
        chmod +x minio
        export MINIO_ROOT_USER=minio
        export MINIO_ROOT_PASSWORD=minio123
        ./minio server /tmp/minio &
      extraWindowsCommand: |
        Invoke-WebRequest -Uri "https://dl.min.io/server/minio/release/windows-amd64/minio.exe" -OutFile "C:\minio.exe"
        Invoke-WebRequest -Uri "https://raw.githubusercontent.com/minio/minio-service/master/windows/install-service.ps1" -OutFile "C:\install-service.ps1"
        C:\install-service.ps1
        net start MinIO  
  
  publish-main-snapshots-to-gpm:
    name: Publish Main Snapshots
    runs-on: ubuntu-latest
    needs: [build-test]
    permissions:
      contents: read
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_USERNAME: "liquibot"
      GIT_PASSWORD: ${{ secrets.LIQUIBOT_PAT_GPM_ACCESS }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repository }}

    - name: Download Multiplatform Artifacts
      uses: actions/download-artifact@v4
      with:
        name: multiplatform-artifacts
        path: ./artifacts

    - name: Verify renamed files
      run: |
        ls -l ./artifacts

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'

      #look for dependencies in maven
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        repositories: |
          [
            {
              "id": "liquibase",
              "url": "https://maven.pkg.github.com/liquibase/liquibase",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true",
                "updatePolicy": "always"
              }
            },
            {
              "id": "liquibase-pro",
              "url": "https://maven.pkg.github.com/liquibase/liquibase-pro",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true",
                "updatePolicy": "always"
              }
            }
          ]
        servers: |
          [
            {
              "id": "liquibase",
              "username": "liquibot",
              "password": "${{ secrets.LIQUIBOT_PAT_GPM_ACCESS }}"
            },
            {
              "id": "liquibase-pro",
              "username": "liquibot",
              "password": "${{ secrets.LIQUIBOT_PAT_GPM_ACCESS }}"
            }
          ]

    - name: Publish to GitHub Packages
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        mvn deploy:deploy-file \
        -Dfile="./artifacts/liquibase-checks-$VERSION.jar" \
        -DgroupId=org.liquibase.ext \
        -DartifactId=liquibase-checks \
        -Dversion=main-SNAPSHOT \
        -Dpackaging=jar \
        -DrepositoryId=liquibase \
        -Durl=https://maven.pkg.github.com/${{ github.repository }} \
        -Dusername=liquibot \
        -Dpassword=${{ env.GIT_PASSWORD }}   
           