name: Test Failure Notification

on:
  repository_dispatch:
    types: [ test-failure ]

permissions:
  contents: read
  id-token: write

jobs:
    slack-notification:
        runs-on: ubuntu-latest
        steps:
        - name: Configure AWS credentials for the nightly-builds-slack-webhook secret
          uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
          with:
            role-to-assume: arn:aws:iam::${{ secrets.VAULT_AWS_ACCOUNT_ID }}:role/vault-grouped-nightly-builds-slack-webhook-2
            aws-region: us-east-1

        - name: Get the nightly-builds-slack-webhook secret from vault
          uses: aws-actions/aws-secretsmanager-get-secrets@2297f9a879480a9e3af9b293ed15c70caf8e1c88 # v3.0.2
          with:
            secret-ids: |
              ,/vault/grouped/nightly-builds-slack-webhook
            parse-json-secrets: true

        - name: Notify Slack on Build Failure
          uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
          env:
            SLACK_COLOR: ${{ github.event.action == 'test-failure' && 'danger' || 'good' }}
            SLACK_MESSAGE: "View details on GitHub Actions: ${{ github.event.client_payload.server_url }}/${{ github.event.client_payload.repository }}/actions/runs/${{ github.event.client_payload.run_id }} <@U042HRTL4DT>. Triggered by repository: ${{ github.event.client_payload.repository }} and job: ${{ github.job }}"
            SLACK_TITLE: "❌ ${{ github.event.client_payload.repository }} ❌ Tests failed on branch ${{ github.event.client_payload.branch }} for commit ${{ github.event.client_payload.sha }} in repository ${{ github.event.client_payload.repository }} Workflow File Name: ${{ github.event.client_payload.workflow_name }}"
            SLACK_USERNAME: liquibot
            SLACK_WEBHOOK: ${{ env.NIGHTLY_BUILDS_SLACK_WEBHOOK }}
            SLACK_ICON_EMOJI: ":robot_face:"
            SLACK_FOOTER: "${{ github.event.client_payload.repository }}"
            SLACK_LINK_NAMES: true
