name: Sync Vault Secrets to GitHub Dependabot

on:
  schedule:
    # Run every month on 28th day of the month at 3 AM UTC
    - cron: "0 3 28 */1 *"
  workflow_dispatch:
    # Allow manual triggering

permissions:
  contents: read
  id-token: write

jobs:
  sync-secrets:
    name: Sync PAT from AWS Vault to GitHub Dependabot Secrets
    runs-on: ubuntu-latest
    steps:

    - name: Configure AWS credentials for vault access
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.LIQUIBASE_VAULT_OIDC_ROLE_ARN }}
        aws-region: us-east-1

    - name: Get secrets from vault
      id: vault-secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          ,/vault/liquibase
        parse-json-secrets: true

    - name: Update GitHub Dependabot secret
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Get the PAT from vault and immediately mask it
        PAT_VALUE="${{ env.LIQUIBOT_PAT_GPM_ACCESS }}"
        echo "::add-mask::$PAT_VALUE"
        
        if [ -z "$PAT_VALUE" ]; then
          echo "Error: PAT not found in vault secrets"
          exit 1
        fi
        
        # Use GitHub CLI to update Dependabot secret (simpler than manual API encryption)
        echo "$PAT_VALUE" | gh secret set LIQUIBOT_PAT_GPM_ACCESS --app dependabot --repo ${{ github.repository }}
        
        if [ $? -eq 0 ]; then
          echo "✅ Successfully updated LIQUIBOT_PAT_GPM_ACCESS Dependabot secret"
        else
          echo "❌ Failed to update Dependabot secret using GitHub CLI"
          exit 1
        fi
