name: Sync Vault Secrets to GitHub Dependabot

on:
  schedule:
    # Run every month on 28th day of the month at 3 AM UTC
    - cron: "0 3 28 */1 *"
  workflow_dispatch:
    # Allow manual triggering

permissions:
  contents: read
  id-token: write

jobs:
  sync-secrets:
    name: Sync PAT from AWS Vault to GitHub Dependabot Secrets
    runs-on: ubuntu-latest
    steps:

    - name: Configure AWS credentials for vault access
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.LIQUIBASE_VAULT_OIDC_ROLE_ARN }}
        aws-region: us-east-1

    - name: Get secrets from vault
      id: vault-secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          ,/vault/liquibase
        parse-json-secrets: true

    - name: Get GitHub App token
      id: get-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ env.LIQUIBASE_GITHUB_APP_ID }}
        private-key: ${{ env.LIQUIBASE_GITHUB_APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Set org-level Dependabot secret (visible to ALL repos)
      env:
         GH_TOKEN: ${{ steps.get-token.outputs.token }}
      run: |
         # Read the value exported by the previous step (parse-json-secrets=true)
         PAT_VALUE="${LIQUIBOT_PAT_GPM_ACCESS:-}"
         if [ -z "$PAT_VALUE" ]; then
            echo "Error: LIQUIBOT_PAT_GPM_ACCESS not found in Secrets Manager payload"
            exit 1
          fi
          echo "::add-mask::$PAT_VALUE"

          # Create/Update org Dependabot secret for ALL repositories
          printf "%s" "$PAT_VALUE" | gh secret set LIQUIBOT_PAT_GPM_ACCESS \
            --app dependabot \
            --org liquibase \
            --visibility all

          echo "✅ Set org Dependabot secret LIQUIBOT_PAT_GPM_ACCESS for all repos"